const { MAP_W, MAP_H, COLORS, FOOD_TYPES, WEAPON_TYPES } = require('../shared/constants');

const PORT = parseInt(process.env.PORT || '20021', 10);
const TICK_RATE = 30;
const BOT_NAMES = ['MooCow','BurgerBoy','SteakMate','DairyQueen','CowPoke','BeefCake','MilkMan','Cheddar','UdderChaos','MooLander','CowntDracula','SirLoin','AngusYoung','T-Bone','Bovinity','Cowculator','MooDonna','Heifernator','PrimeMooVer','Bullseye','CreamPuff','Grazey','Moosician','Barnaby','Wagyu','Bessie','Clarabelle','Hoofdini','ButterScotch','Daisy','Clover','MilkDud','MozzaMoo','MooStache','Brisket','Rumpsteak','Ferdinand','Cashmoo','DrMoo','MooJesty','MooTang','JellyBean','CowRupt','Brie','Ribeye','Holstein','LadyMoo','PattyMelt','Longhorn','MooFasa','Cowbell','Cuddles','Gruyere','Feta','MooShiesty'];

const BOT_CHAT_LINES = [
  "get udder'd, loser",
  "that was a mooving experience",
  "got milked lol",
  "i'm lactose intolerant to your L's",
  "this ain't your pasture",
  "cud i BE any better?",
  "steaks are high, homie",
  "hoof would've thought",
  "moo-ve aside peasant",
  "i'm the gr8est of all thyme",
  "ez dubs",
  "spit gun is meta btw",
  "prepare to be grilled",
  "nobody puts baby in the corner... of this map",
  "how now brown cow",
  "you couldn't hit a barn broadside",
  "im the cream of the crop",
  "no beef?",
  "got the moo-jo working",
  "milk before cereal pls",
  "hope u brought a straw",
  "time to churn butter",
  "send it",
  "thats a nah from me dawg",
  "cowabunga it is",
  "rare steak only",
  "udderly embarrassing for you",
  "the pasture is mine",
  "bro thought he was something",
  "beef is served",
  "moooove",
  "i'll be taking that udder",
  // Rust references (cowified)
  "Do you like Pizza",
  "rat you out my udder",
  "kos, no u",
  "offline my barn bro",
  "that's my loot, naked",
  "nakeds out, suited in",
  "roof camping w/ the L9",
  "you just got countered at the moo-cade",
  "bag check the corpse",
  "farming hemp with my cud",
  "wiped ur barn, ez",
  "heli on the map, cows beware",
  "sulfur before stew, always",
  "no honor in this server, only udder",
  "got raided, lost everything except the cows",
  "the meadow is cruel",
  "metal bbq hours",
  "i dropped a satchel on your hay bale",
  "my moo-zine is fuller than yours",
  "build tower, farm udder, repeat",
];

module.exports = { PORT, TICK_RATE, MAP_W, MAP_H, COLORS, FOOD_TYPES, WEAPON_TYPES, BOT_NAMES, BOT_CHAT_LINES };
